apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    temporary-test-resources: "true"
  name: temporary-test-resources
  namespace: temporary-test-resources
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: regional-ssd-test